---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: frontend
spec:
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: web-apps
spec:
  type: url
  targets:
    - https://github.com/asifhafeez89/collinsonx-web-copy/tree/main/apps/booking/catalog-info.yaml
    - https://github.com/asifhafeez89/collinsonx-web-copy/tree/main/apps/partner-management/catalog-info.yaml
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: collinsonx-web
  description: Frontend Applications serving multiple projects.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: CollinsonX/collinsonx-web
  tags:
    - internal
    - monorepo
  links:
    - url: https://lifestyle-x-wiki.atlassian.net/wiki/spaces/LIFESTYLEX/pages/174391841/Engineer+Onboarding
      title: Engineer Onboarding
      icon: book
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: frontend
  providesApis:
    - partner-management
    - booking
