name: Build and Deploy Storybook to Test and UAT environments

on:
  push:
    branches:
      - main
    paths:
      - 'packages/collinsonx-storybook/**'
      - 'packages/**'
      - '.github/workflows/build-deploy-storybook.yml'

jobs:
  build-deploy-to-test:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: 'dev'
      deployment-url: 'cergea-storybook.vercel.app'
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.STORYBOOK_VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  build-deploy-to-uat:
    needs: build-deploy-to-test
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: 'uat'
      deployment-url: 'cergea-storybook-uat.vercel.app'
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.STORYBOOK_VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
