name: run e2e web tests - partner portal

on:
  pull_request:
    branches: ['dev']
    paths:
      - 'apps/partner-management/**'
      - '.github/workflows/e2e-tests-partner.yaml'
      - 'packages/**'

jobs:
  e2e-test-partner:
    runs-on: e2e-test-runner
    container:
      image: mcr.microsoft.com/playwright:v1.40.1-focal
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i

      - name: Define host mappings (required by cors)
        run: |
          apt-get update -y
          apt-get install sudo -y
          sudo echo "127.0.0.1 partner-local.test.cergea.com" | sudo tee -a /etc/hosts

      - name: Partner webapp SSL cert creation (required by cors)
        run: |
          apt-get install wget libnss3-tools lsof -y
          wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
          mv mkcert-v1.4.3-linux-amd64 /usr/bin/mkcert
          chmod +x /usr/bin/mkcert
          cd apps/partner-management
          mkcert -key-file partner-local.test.cergea.com-key.pem -cert-file partner-local.test.cergea.com.pem partner-local.test.cergea.com
          echo "${{ secrets.PARTNER_APP_ENV_FILE }}" > .env.local

      - name: Run partner portal tests
        run: |
          export INSTRUMENT_CODE=1
          pnpm run build --filter partner-management
          pnpm add --global pm2
          cd apps/partner-management
          pm2 --name dev-server --interpreter bash start pnpm -- dev:test

          attempt_counter=0
          max_attempts=5

          until $(curl --output /dev/null --silent --head --fail http://localhost:3010); do
            if [ ${attempt_counter} -eq ${max_attempts} ];then
              echo "Max attempts reached"
              exit 1
            fi

            printf '.'
            attempt_counter=$(($attempt_counter+1))
            sleep 5
          done

          export DD_CIVISIBILITY_AGENTLESS_ENABLED=true
          export DD_API_KEY=${{ secrets.DATADOG_API_KEY }}
          export DD_SITE="datadoghq.eu"
          export NODE_OPTIONS="-r dd-trace/ci/init"
          export DD_ENV=ci
          export DD_TAGS="test_type:browser"

          echo "${{ secrets.ENV_TESTS_FILE_PARTNER }}" > .env.tests
          pnpm e2e:ci-partner-portal

      - name: Upload partner portal test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: apps/partner-management/playwright-report

      - name: Run partner portal accessibility tests (non-blocking)
        id: accessibility
        run: |
          cd apps/partner-management
          pnpm e2e:ci-partner-portal-accessibility || true

      - name: Upload partner portal accessibility test results
        if: steps.accessibility.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: playwright-accessibility-report
          path: apps/partner-management/playwright-report

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs

      - name: Upload coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-coverage
          path: apps/partner-management/.nyc_output
