name: run e2e web tests

on:
  pull_request:

jobs:
  test:
    runs-on: e2e-test-runner
    container:
      image: mcr.microsoft.com/playwright:v1.32.0-focal
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i

      - name: Define host mappings (required by cors)
        run: |
          apt-get update -y
          apt-get install sudo -y
          sudo echo "127.0.0.1 partner-local.uat.cergea.com" | sudo tee -a /etc/hosts

      - name: Partner webapp SSL cert creation (required by cors)
        run: |
          apt-get install wget libnss3-tools lsof -y
          wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
          mv mkcert-v1.4.3-linux-amd64 /usr/bin/mkcert
          chmod +x /usr/bin/mkcert
          cd apps/partner-management
          mkcert -key-file partner-local.uat.cergea.com-key.pem -cert-file partner-local.uat.cergea.com.pem partner-local.uat.cergea.com
          echo "${{ secrets.ENV_LOCAL_FILE }}" > .env.local

      - name: Run partner webapp tests
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: |
          export INSTRUMENT_CODE=1

          pnpm run build
          pnpm add --global pm2
          pm2 --name dev-server --interpreter bash start pnpm -- dev

          attempt_counter=0
          max_attempts=5

          until $(curl --output /dev/null --silent --head --fail http://localhost:3010); do
            if [ ${attempt_counter} -eq ${max_attempts} ];then
              echo "Max attempts reached"
              exit 1
            fi

            printf '.'
            attempt_counter=$(($attempt_counter+1))
            sleep 5
          done

          export DD_CIVISIBILITY_AGENTLESS_ENABLED=true
          export DD_API_KEY=${{ secrets.DATADOG_API_KEY }}
          export DD_SITE="datadoghq.eu"
          export NODE_OPTIONS="-r dd-trace/ci/init"
          export DD_ENV=ci
          export DD_TAGS="test_type:browser"

          echo "${{ secrets.ENV_TESTS_FILE }}" > packages/collinsonx-tests-e2e/.env.tests
          pnpm --filter "@collinsonx/tests-e2e" e2e:local-partner-ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: packages/collinsonx-tests-e2e/playwright-report

      - name: Upload coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-coverage
          path: packages/collinsonx-tests-e2e/.nyc_output
