name: run e2e web tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.0-focal
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i

      - name: "Run build, start server then run tests"
        run: |
          pnpm run build
          pnpm add --global pm2
          pm2 --name dev-server start pnpm -- start

          export DD_CIVISIBILITY_AGENTLESS_ENABLED=true
          export DD_API_KEY=${{ secrets.DATADOG_API_KEY }}
          export DD_SITE="datadoghq.eu"
          export NODE_OPTIONS="-r dd-trace/ci/init"
          export DD_ENV=ci
          export DD_TAGS="test_type:browser"

          cd packages/collinsonx-tests-e2e
          pnpm run e2e:start

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: packages/collinsonx-tests-e2e/playwright-report
