name: run e2e web tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.0-focal
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i

      - name: Define host mappings (required by cors)
        run: |
          apt-get update -y
          apt-get install sudo -y
          sudo echo "127.0.0.1 partner-local.uat.cergea.com" | sudo tee -a /etc/hosts
      
      - name: Partner webapp SSL cert creation (required by cors)
        run: |
          apt-get install wget libnss3-tools lsof -y
          wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
          mv mkcert-v1.4.3-linux-amd64 /usr/bin/mkcert
          chmod +x /usr/bin/mkcert
          cd apps/partner-management
          mkcert -key-file partner-local.uat.cergea.com-key.pem -cert-file partner-local.uat.cergea.com.pem partner-local.uat.cergea.com
          echo "${{ secrets.ENV_LOCAL_FILE }}" > .env.local

      - name: Run partner webapp tests
        run: |
          apt-get update -y
          apt-get install -y netcat
          pnpm run build
          pnpm add --global pm2
          pm2 --name dev-server start pnpm -- dev
          pm2 logs dev-server
          sleep 20
          echo -n "GET / HTTP/1.1\r\nHost: localhost\r\n\r\n" | nc localhost 3010
          curl http://localhost:3010 -verbose

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: packages/collinsonx-tests-e2e/playwright-report
