name: PR Unit Tests

on:
  pull_request:
    branches: ['main']
  merge_group:
    types: [checks_requested]

jobs:
  # Job to run change detection
  changes:
    name: Detect changes for apps
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step 
    # this could be used to explicitily run tests for changed apps only
    outputs:
      apps: ${{ steps.filter.outputs.src }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'apps/booking/**'
            - 'apps/partner-management/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.apps == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install packages
        run: pnpm i
      - name: Run Unit Tests
        run: |
          export DD_CIVISIBILITY_AGENTLESS_ENABLED=true
          export DD_API_KEY=${{ secrets.DATADOG_API_KEY }}
          export DD_SITE="datadoghq.eu"
          export NODE_OPTIONS="-r dd-trace/ci/init"
          export DD_ENV=ci
          export DD_TAGS="test_type:unit"
          pnpm run test:ci --filter="[origin/main...HEAD]"
