name: Build & Publish TechDocs Site

on:
  push:
    branches: docs/NEE-355-backstage

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      TECHDOCS_S3_BUCKET_NAME: collinsonx-backstage

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::328645840678:role/backstage-s3-role
          aws-region: eu-west-1
          role-session-name: collinson-backend-techdocs-pipeline

      - name: Build and publish backend-apps root techdocs
        run: pnpm run techdocs

      - name: Build and publish individual API docs
        run: pnpm run techdocs:all
